[package]
name = "file_storage_integrity"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "file_storage_integrity"

[dependencies]
hc_zome_file_storage_integrity = "0.2"
hdi = { workspace = true }

serde = { workspace = true }
